version: '2'
services:
  nginx-proxy:
    image: docker.io/nginx:1.14-alpine
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/www:/data/www/
    env_file:
      - .env
    restart: always

  couchdb:
    image: docker.io/couchdb:2.2
    ports:
      - '${COUCHDB_PORT}:5984'
    environment:
      # CouchDB admin credentials
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ${COUCHDB_ADMIN_PASSWORD}
    depends_on:
      - 'nginx-proxy'
    volumes:
      - ${COUCHDB_DATA_DIRECTORY}:/opt/couchdb/data
    env_file:
      - .env
    restart: always

  node-pdb-sync:
    build: ./node-pdb-sync
    restart: always
    privileged: true
    depends_on:
      - 'couchdb'
    volumes:
      - ./pdb-assembly-data:/pdb-assembly-data
      - ./pdb-data:/pdb-data
      - ./logs:/logs
      #     - ./node-pdb-sync/src:/node-pdb
      - ./.env:/node-pdb/.env
    #    tty: true
    environment:
      - DEBUG=*
    command: npm run cron
