-- Drop the composite covering index on ligand_ss_index.
--
-- The index was originally meant to accelerate the bitwise containment
-- screen in substructureSearch.js:
--
--   WHERE (ss_index0 & ?) = ? AND (ss_index1 & ?) = ? … AND (ss_index7 & ?) = ?
--
-- Bitwise predicates of the form `(col & ?) = ?` are not sargable, so
-- SQLite cannot seek with the B-tree — the only thing the index could
-- contribute is a covering scan that skips the table heap. But because
-- ligand_ss_index already lives in its own narrow table (PK `code` +
-- 8 INTEGER columns), the heap IS the covering scan target. The index
-- is roughly the same size as the heap (8 INTEGERs + rowid vs
-- 8 INTEGERs + short TEXT), and EXPLAIN QUERY PLAN confirms the
-- planner ignores it: it always picks `SCAN ligand_ss_index` over the
-- heap, never `SCAN … USING INDEX idx_ligand_ss_index`.
--
-- Keeping the index inflates disk usage and slows every CCD insert
-- for no read benefit. Drop it.

DROP INDEX IF EXISTS idx_ligand_ss_index;
