-- Migration 003: pre-computed stats rollup tables and molecule_type column.
--
-- Adds:
--   * molecule_type TEXT on pdb_entries — populated by upsertPdbEntrySync
--     going forward and back-filled here for all existing rows.
--   * idx_pdb_entries_molecule_type — makes GROUP BY molecule_type instant.
--   * idx_pdb_entries_helices_sheets — composite index so the helices-vs-sheets
--     scatter chart can GROUP BY both columns via an index scan.
--   * stats_helix_length_hist / stats_helix_kind_hist / stats_sheet_length_hist
--     — pre-rolled histograms that replace the O(N) full-table-scan queries.
--   * stats_residue_freq — pre-rolled per-residue totals across all PDB entries,
--     replacing the O(N) GROUP BY scans in aminoAcidFreq / nucleicBaseFreq.
--
-- All rollup tables are regenerated by rebuildStatsRollup() at the end of
-- every rsync cycle; the initial INSERT statements below populate them from
-- whatever data exists at migration time.

ALTER TABLE pdb_entries ADD COLUMN molecule_type TEXT;

CREATE INDEX IF NOT EXISTS idx_pdb_entries_molecule_type
  ON pdb_entries(molecule_type);

CREATE INDEX IF NOT EXISTS idx_pdb_entries_helices_sheets
  ON pdb_entries(nb_helices, nb_sheets);

CREATE TABLE IF NOT EXISTS stats_helix_length_hist (
  length INTEGER NOT NULL PRIMARY KEY,
  count  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stats_helix_kind_hist (
  kind  INTEGER NOT NULL PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stats_sheet_length_hist (
  length INTEGER NOT NULL PRIMARY KEY,
  count  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stats_residue_freq (
  residue     TEXT    NOT NULL PRIMARY KEY,
  total_count INTEGER NOT NULL DEFAULT 0
);

-- Back-fill molecule_type for all existing entries from pdb_residue_counts.
UPDATE pdb_entries
SET molecule_type = (
  SELECT CASE
    WHEN MAX(CASE WHEN rc.residue IN (
           'ALA','ARG','ASN','ASP','CYS','GLU','GLN','GLY','HIS','ILE',
           'LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL'
         ) THEN 1 ELSE 0 END) = 1
     AND MAX(CASE WHEN rc.residue IN (
           'DA','DC','DG','DT','DU','A','C','G','U','T'
         ) THEN 1 ELSE 0 END) = 1 THEN 'hybrid'
    WHEN MAX(CASE WHEN rc.residue IN (
           'ALA','ARG','ASN','ASP','CYS','GLU','GLN','GLY','HIS','ILE',
           'LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL'
         ) THEN 1 ELSE 0 END) = 1 THEN 'protein'
    WHEN MAX(CASE WHEN rc.residue IN (
           'DA','DC','DG','DT','DU','A','C','G','U','T'
         ) THEN 1 ELSE 0 END) = 1 THEN 'nucleic'
    ELSE 'other'
  END
  FROM pdb_residue_counts rc WHERE rc.pdb_id = pdb_entries.id
);

INSERT INTO stats_helix_length_hist (length, count)
SELECT (res_to - res_from + 1), COUNT(*)
FROM pdb_helices
WHERE res_to >= res_from
  AND (res_to - res_from + 1) BETWEEN 1 AND 200
GROUP BY (res_to - res_from + 1);

INSERT INTO stats_helix_kind_hist (kind, count)
SELECT kind, COUNT(*)
FROM pdb_helices
WHERE kind IS NOT NULL
GROUP BY kind;

INSERT INTO stats_sheet_length_hist (length, count)
SELECT (res_to - res_from + 1), COUNT(*)
FROM pdb_sheets
WHERE res_to >= res_from
  AND (res_to - res_from + 1) BETWEEN 1 AND 200
GROUP BY (res_to - res_from + 1);

INSERT INTO stats_residue_freq (residue, total_count)
SELECT residue, SUM(count)
FROM pdb_residue_counts
GROUP BY residue;
