-- Migration 004: covering indexes + pre-computed rollup tables for slow stats queries.
--
-- Adds:
--   * Six covering indexes on pdb_entries — turns the GROUP BY full-table-scan
--     queries (179–344 ms each) into index-only scans.
--   * ligands.nb_pdbs — cached count column replacing the correlated subquery
--     fired on every ligand-browse request.
--   * stats_ligand_freq / stats_ligand_mw_hist — pre-computed pdb_formulas
--     aggregations (701 ms + 265 ms → <5 ms each).
--   * stats_ec_classes — pre-computed EC class distribution (198 ms → <5 ms).
--   * stats_residues_histogram — pre-bucketed residue histogram replacing the
--     239 k-row raw fetch to JavaScript (112 ms + JS cost → <5 ms).
--
-- All rollup tables are regenerated by rebuildStatsRollup() at the end of
-- every rsync cycle. The initial INSERT statements below seed them from
-- whatever data exists at migration time.

-- ---- Covering indexes on pdb_entries ----------------------------------------

CREATE INDEX IF NOT EXISTS idx_pdb_entries_chains
  ON pdb_entries(nb_chains);

CREATE INDEX IF NOT EXISTS idx_pdb_entries_iep
  ON pdb_entries(iep);

CREATE INDEX IF NOT EXISTS idx_pdb_entries_modified_residues
  ON pdb_entries(nb_modified_residues);

-- Composite indexes let SQLite satisfy the whole GROUP BY with an index scan.
CREATE INDEX IF NOT EXISTS idx_pdb_entries_year_experiment
  ON pdb_entries(year, experiment);

CREATE INDEX IF NOT EXISTS idx_pdb_entries_year_nb_ligands
  ON pdb_entries(year, nb_ligands);

CREATE INDEX IF NOT EXISTS idx_pdb_entries_year_nb_residues
  ON pdb_entries(year, nb_residues);

-- ---- Cached count on ligands -------------------------------------------------

ALTER TABLE ligands ADD COLUMN nb_pdbs INTEGER NOT NULL DEFAULT 0;

UPDATE ligands
SET nb_pdbs = (
  SELECT COUNT(*) FROM pdb_ligands WHERE pdb_ligands.ligand_code = ligands.code
);

-- ---- Pre-computed rollup tables ---------------------------------------------

-- Aggregated ligand frequency across all PDB assemblies (replaces 701 ms
-- full scan of pdb_formulas ordered by SUM(count)).
CREATE TABLE IF NOT EXISTS stats_ligand_freq (
  label TEXT    NOT NULL PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);

-- Ligand molecular-weight histogram (replaces 265 ms full scan of pdb_formulas).
CREATE TABLE IF NOT EXISTS stats_ligand_mw_hist (
  key   INTEGER NOT NULL PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);

-- EC class distribution (replaces 198 ms COUNT(DISTINCT pdb_id) on pdb_chains).
CREATE TABLE IF NOT EXISTS stats_ec_classes (
  head  TEXT    NOT NULL PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);

-- Pre-bucketed residue-count histogram (replaces 239 k-row fetch to JS).
-- Buckets match RESIDUES_HISTOGRAM_BINS = [50,100,200,500,1000,2000,5000,10000].
CREATE TABLE IF NOT EXISTS stats_residues_histogram (
  key   INTEGER NOT NULL PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);

-- ---- Initial population ------------------------------------------------------

INSERT INTO stats_ligand_freq (label, value)
SELECT label, SUM(count)
FROM pdb_formulas
WHERE label <> 'HOH'
GROUP BY label;

INSERT INTO stats_ligand_mw_hist (key, value)
SELECT
  CASE
    WHEN mw <  100 THEN 0
    WHEN mw <  250 THEN 100
    WHEN mw <  500 THEN 250
    WHEN mw < 1000 THEN 500
    WHEN mw < 2000 THEN 1000
    WHEN mw < 5000 THEN 2000
    ELSE 5000
  END AS key,
  COUNT(*) AS value
FROM pdb_formulas
WHERE label <> 'HOH' AND mw IS NOT NULL AND mw > 0
GROUP BY key;

INSERT INTO stats_ec_classes (head, value)
SELECT head, COUNT(DISTINCT pdb_id) AS value
FROM (
  SELECT pdb_id, substr(ec, 1, 1) AS head
  FROM pdb_chains
  WHERE ec IS NOT NULL
    AND length(ec) > 0
    AND substr(ec, 1, 1) BETWEEN '1' AND '7'
)
GROUP BY head;

INSERT INTO stats_residues_histogram (key, value)
SELECT
  CASE
    WHEN nb_residues <    50 THEN 0
    WHEN nb_residues <   100 THEN 50
    WHEN nb_residues <   200 THEN 100
    WHEN nb_residues <   500 THEN 200
    WHEN nb_residues <  1000 THEN 500
    WHEN nb_residues <  2000 THEN 1000
    WHEN nb_residues <  5000 THEN 2000
    WHEN nb_residues < 10000 THEN 5000
    ELSE 10000
  END AS key,
  COUNT(*) AS value
FROM pdb_entries
WHERE nb_residues > 0
GROUP BY key;
