import { appendFileSync, existsSync, statSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { gunzip } from 'node:zlib';

import createDebug from 'debug';

import getConfig from './config.js';
import { getLigandsDB } from './db/getDB.js';
import { replacePdbLigandInstancesSync } from './db/insertPdbLigandInstances.js';
import { markAssemblySync, upsertPdbEntrySync } from './db/upsertPdbEntry.js';
import { parse as parsePdb } from './util/pdbParser.js';
import pymol, { pymolImagePath } from './util/pymol.js';

const ungzip = promisify(gunzip);
const MAX_BUFFER_LENGTH = 150 * 1024 * 1024;

const debug = createDebug('pdb-sync:common');
const config = getConfig();

/**
 * JSON-lines log capturing every PyMol render failure (one row per
 *  `{ pdbId, size }` attempt). Lives next to the PNGs so operators can
 *  `tail -f` it and post-process without touching the sqlite volume.
 */
const pymolFailuresLogPath = join(config.pymolDir, 'failures.log');

/**
 * Append a render failure record to the on-disk JSON-lines log. Failures of
 * the log write itself (full disk, permissions) are swallowed so a bad log
 * never propagates back and aborts the rsync / rebuild loop.
 *
 * `stderr` and `stdout` are tail-truncated (last 2000 / 500 chars) so a
 * pathological pymol run cannot bloat the log; that's enough to keep the
 * actual error message at the end of the stream.
 * @param {{
 *   pdbId: string,
 *   width: number,
 *   height: number,
 *   stage?: 'pymol' | 'graphicsmagick',
 *   exitCode?: number | null,
 *   signal?: string | null,
 *   error: string,
 *   stderr?: string,
 *   stdout?: string,
 *   cmd?: string,
 * }} entry - Failure record to persist.
 */
function logPymolFailure(entry) {
  const line = JSON.stringify({
    timestamp: new Date().toISOString(),
    ...entry,
  });
  try {
    appendFileSync(pymolFailuresLogPath, `${line}\n`);
  } catch {
    // ignore
  }
}

/**
 * Extract the 4-character PDB id from a `pdb<id>.ent.gz` or `<id>.pdb1.gz`
 * filename. Always lowercased; callers uppercase as needed.
 * @param {string} filename - Path or basename containing the PDB id.
 * @returns {string} Lowercased PDB id (or empty string if it cannot be parsed).
 */
export function getIdFromFileName(filename) {
  return filename
    .replace(/^.*\/pdb([^.]*)\.ent\.gz/, '$1')
    .replace(/^.*\/([^.]*)\.pdb1.gz/, '$1');
}

/**
 * Parse a single asymmetrical-unit `.ent.gz` file and persist its parsed
 * metadata to sqlite. The original gzipped file stays on disk and is the
 * single source of truth for the PDB binary; the API server streams it
 * back on demand.
 * @param {string} filename - Path to the gzipped `.ent` file.
 * @param {object} [options] - Tuning options.
 * @param {boolean} [options.skipTransaction] - When true, the inner sqlite
 *   writes assume the caller has already opened an outer transaction. Used
 *   by the batched rebuild path so 100 files share a single fsync.
 * @returns {Promise<void>}
 */
export async function processPdb(filename, options = {}) {
  debug(`Process: ${filename}`);
  const id = getIdFromFileName(filename).toUpperCase();
  if (id.length !== 4) {
    debug(`Skipping ${filename}: cannot extract PDB id`);
    return;
  }
  const data = await readFile(filename);
  const buffer = await ungzip(data);
  const parsed = parsePdb(buffer.toString());

  const skipTransaction = Boolean(options.skipTransaction);
  const db = await getLigandsDB();
  upsertPdbEntrySync(db, id, parsed, {
    rawSize: buffer.length,
    skipTransaction,
  });
  replacePdbLigandInstancesSync(db, id, parsed.ligandInstances || [], {
    skipTransaction,
  });
  debug('Entry saved:', id);
}

/**
 * Process a list of asymmetrical-unit files sequentially. Errors on one file
 * do not stop processing of the remaining files.
 * @param {string[]} files - Paths to gzipped `.ent.gz` files.
 * @returns {Promise<void>}
 */
export async function processPdbs(files) {
  /* eslint-disable no-await-in-loop -- intentional sequential sqlite writes */
  for (const file of files) {
    try {
      await processPdb(file);
    } catch (error) {
      debug('Exception for file:', file, error);
    }
  }
  /* eslint-enable no-await-in-loop */
}

/**
 * @typedef {object} AssemblyRenderStats
 * @property {number} rendered - PNG sizes that were generated by PyMol.
 * @property {number} skipped - PNG sizes that already existed and were kept.
 * @property {number} failed - PNG sizes whose render attempt threw.
 */

/**
 * Render and persist PyMol bio-assembly thumbnails for `filename`. The
 * decompressed `.pdb1` file is not stored anywhere — the API server gunzips
 * the `.gz` archive on the fly.
 *
 * Idempotency: pre-existing PNGs at the same size are kept when invoked from
 * the rebuild path (`forceRender: false`, the default), which keeps
 * `npm run rebuild-db` fast to re-run. The rsync path passes
 * `forceRender: true` so that an entry replaced upstream gets fresh
 * thumbnails instead of inheriting the stale ones.
 *
 * Per-render outcomes are aggregated into the returned `AssemblyRenderStats`
 * and every failure is appended to `data/pymol/failures.log` for offline
 * triage.
 * @param {string} filename - Path to the gzipped `.pdb1` bio-assembly file.
 * @param {object} [options] - Tuning options.
 * @param {boolean} [options.forceRender] - When true, existing PNGs are
 *   unlinked before re-rendering. Used by the rsync path.
 * @returns {Promise<AssemblyRenderStats>} Counts for this single file.
 */
export async function processPdbAssembly(filename, options = {}) {
  const stats = { rendered: 0, skipped: 0, failed: 0 };
  const id = getIdFromFileName(filename).toUpperCase();
  if (id.length !== 4) {
    debug(`Skipping ${filename}: cannot extract PDB id`);
    return stats;
  }
  debug('Process pdb assembly:', id);

  const data = await readFile(filename);
  const buffer = await ungzip(data);

  if (buffer.length >= MAX_BUFFER_LENGTH) {
    debug(`Skipping ${id}: assembly too large (${buffer.length} bytes)`);
    return stats;
  }

  const force = Boolean(options.forceRender);
  const sizes = config.pymol ?? [];
  /* eslint-disable no-await-in-loop -- pymol is heavy; render sequentially */
  for (const size of sizes) {
    const target = pymolImagePath(config.pymolDir, id, size.width, size.height);
    try {
      const result = await pymol(id, buffer, target, { ...size, force });
      if (result.status === 'rendered') {
        stats.rendered++;
      } else {
        stats.skipped++;
      }
    } catch (error) {
      stats.failed++;
      const message = error instanceof Error ? error.message : String(error);
      debug(
        `pymol render failed for ${id} ${size.width}x${size.height}:`,
        message,
      );
      const stderr = typeof error?.stderr === 'string' ? error.stderr : '';
      const stdout = typeof error?.stdout === 'string' ? error.stdout : '';
      logPymolFailure({
        pdbId: id,
        width: size.width,
        height: size.height,
        stage: error?.stage ?? 'pymol',
        exitCode: error?.code,
        signal: error?.signal,
        error: message,
        stderr: stderr.slice(-2000),
        stdout: stdout.slice(-500),
        cmd: error?.cmd,
      });
    }
  }
  /* eslint-enable no-await-in-loop */

  const db = await getLigandsDB();
  markAssemblySync(db, id, buffer.length);
  return stats;
}

/**
 * Process a list of bio-assembly files sequentially. Errors on one file do
 * not stop the remaining files.
 * @param {string[]} files - Paths to `.pdb1.gz` files.
 * @returns {Promise<void>}
 */
export async function processPdbAssemblies(files) {
  /* eslint-disable no-await-in-loop -- pymol is heavy; render sequentially */
  for (const file of files) {
    try {
      await processPdbAssembly(file);
    } catch (error) {
      debug('Exception for file:', file, error);
    }
  }
  /* eslint-enable no-await-in-loop */
}

/**
 * Build the canonical on-disk path of the gzipped asymmetrical-unit file
 * (`<root>/<bb>/pdb<id>.ent.gz`) for a given PDB id, mirroring the wwPDB
 * `pub/pdb/data/structures/divided/pdb` layout. Pure path arithmetic — does
 * not check for existence.
 * @param {string} root - Local root of the asymmetrical-unit tree.
 * @param {string} pdbId - PDB id (any case).
 * @returns {string} Absolute path to the would-be file.
 */
export function asymUnitPath(root, pdbId) {
  const lower = pdbId.toLowerCase();
  return join(root, lower.slice(1, 3), `pdb${lower}.ent.gz`);
}

/**
 * Build the canonical on-disk path of the gzipped bio-assembly file
 * (`<root>/<bb>/<id>.pdb1.gz`). Pure path arithmetic — does not check for
 * existence.
 * @param {string} root - Local root of the bio-assembly tree.
 * @param {string} pdbId - PDB id (any case).
 * @returns {string} Absolute path to the would-be file.
 */
export function bioAssemblyPath(root, pdbId) {
  const lower = pdbId.toLowerCase();
  return join(root, lower.slice(1, 3), `${lower}.pdb1.gz`);
}

/**
 * Resolve the canonical on-disk path for the gzipped asymmetrical-unit file
 * of a given PDB id. Returns `null` when the file is not present.
 * @param {string} pdbId - PDB id (any case).
 * @returns {{ path: string, size: number } | null} Resolved path + size, or null.
 */
export function findAsymUnitFile(pdbId) {
  const path = asymUnitPath(config.asymetrical.rsync.destination, pdbId);
  if (!existsSync(path)) return null;
  return { path, size: statSync(path).size };
}

/**
 * Resolve the canonical on-disk path for the gzipped bio-assembly file of a
 * given PDB id. Returns `null` when the file is not present.
 * @param {string} pdbId - PDB id (any case).
 * @returns {{ path: string, size: number } | null} Resolved path + size, or null.
 */
export function findAssemblyFile(pdbId) {
  const path = bioAssemblyPath(config.bioAssembly.rsync.destination, pdbId);
  if (!existsSync(path)) return null;
  return { path, size: statSync(path).size };
}
